### PR TITLE
Update documents to pass CRAN check

### PR DESCRIPTION
**Pull request by zkamvar**
Hi @nickreich,

I've done a few things to make sure this passes CRAN checks:

1. Moved the imports to Roxygen tags (otherwise, it replaced them) and re-document
2. add documentation for the unused `y` parameter in the plot method
3. add a `.travis.yml` file to use continuous integration (though you need to set it up: https://travis-ci.org/organizations/nickreich/repositories)

I don't know your policy on contribution authorship, so I didn't add my name to the authors list.

### CODE REVIEW

**Comment by nickreich** [comment]
Thank you! I'd be very happy to have you added as a contributor (or other appropriate authorship label) to the package. Do you want to revise the PR to reflect this?

**Comment by nickreich** [comment]
Also, I've used Travis before for other work, but not for an R package. What does the Travis integration that you've set up do for us?

**Comment by zkamvar** [comment]
> Also, I've used Travis before for other work, but not for an R package. What does the Travis integration that you've set up do for us?

It automatically runs R CMD check any time someone pushes a commit or makes a PR to make sure nothing breaks (https://usethis.r-lib.org/reference/ci.html). If you add unit tests in the future, it will also run those and send coverage stats to https://codecov.io.

**Comment by zkamvar** [comment]
I just realized the link to activate the travis build was incorrect. It should be here: https://travis-ci.org/nickreich/coarseDataTools

**Pull request merged**
